pub mod known_principal;
pub mod provision_empty_canisters_in_a_subnet_test;
pub mod provision_subnet_orchestrator_test;
pub mod recharge_subnet_orchestrator_test;
pub mod register_and_deregister_new_subnet_orchestrator_test;
pub mod test_upgrade_subnet_orchestrator_canister_with_latest_wasm;
pub mod update_canisters_last_access_time_test;
