pub mod get_index_details_is_user_name_taken;
pub mod get_requester_principals_canister_id_create_if_not_exists_and_optionally_allow_referrer;
pub mod get_user_canister_id_from_unique_user_name;
pub mod get_user_canister_id_from_user_principal_id;
pub mod get_user_index_canister_count;
pub mod update_index_with_unique_user_name_corresponding_to_user_principal_id;
