pub mod hot_or_not_timely_index_update_test;
pub mod hotornot_game_simulation_test;
pub mod yral_game_simulation_test;
pub mod reconcile_scores_test;
pub mod when_bob_charlie_dan_place_bet_on_alice_created_post_then_expected_outcomes_occur;
pub mod timers_test;
pub mod receive_call_from_canister;
