pub mod receive_all_token_transactions_from_individual_user_canister;
pub mod receive_all_user_posts_from_individual_user_canister;
pub mod receive_current_token_balance_from_individual_user_canister;
pub mod receive_principals_i_follow_from_individual_user_canister;
pub mod receive_principals_that_follow_me_from_individual_user_canister;
pub mod receive_profile_details_from_individual_user_canister;
pub mod restore_backed_up_data_to_individual_users_canister;
