pub mod provision_new_available_and_backup_canister_on_signups_if_required;
pub mod recharge_individual_canister_when_requested;
pub mod test_allot_empty_canisters_to_individual_canister;
pub mod test_mark_subnet_orchestrator_as_maxed_out_once_backup_canisters_are_consumed;
pub mod test_updating_controller_before_upgrading_invidividual_canister;
